<?php

namespace Oa\Model;
use Zend\Db\TableGateway\TableGateway;
use Oa\Model\Userinfo;
use Oa\Model\BaseTable;

class UserinfoTable extends BaseTable
{
    public $tableModel = 'Oa\Model\Userinfo';
    public $tableName = 'userinfo';

    public function saveAs(Userinfo $obj)
    {
        return parent::save($obj); // TODO: Change the autogenerated stub
    }

    public function getPaginator($where = null , $order = null)
    {
        return parent::_getPaginator( $where , $order); // TODO: Change the autogenerated stub
    }

}



?>
