<?php

namespace Oa\Model;
use Zend\Db\TableGateway\TableGateway;
use Oa\Model\Origin;
use Oa\Model\BaseTable ;
class OriginTable extends BaseTable
{
    public $tableName = 'origin';
    public $tableModel = 'Oa\Model\Origin';

   public function saveAs(Origin $obj)
   {
       return parent::save($obj); // TODO: Change the autogenerated stub
   }

    public function getPaginator($where = null,$order = null)
    {
        return parent::_getPaginator($where,$order); // TODO: Change the autogenerated stub
    }

}



?>
