<?php

namespace Oa\Model;
use Zend\Db\TableGateway\TableGateway;
use Oa\Model\BaseTable;
class RuleTable extends BaseTable
{
    public $tableName = 'rule';
    public $tableModel = 'Oa\Model\Rule';
    public function saveAs(Rule $rule) 
    {
        return parent::save($rule);
    }

    public function getPaginator($where = null, $order = null)
    {
        return parent::_getPaginator($where, $order); // TODO: Change the autogenerated stub
    }


}



?>
