<?php

namespace Oa\Model;

use Oa\Model\BaseTable;

class StandardTable extends BaseTable
{
    public $tableModel = 'Oa\Model\Standard';
    public $tableName = 'standard';

    public function saveAs(Standard $obj)
    {
        return parent::save($obj); // TODO: Change the autogenerated stub
    }

    public function getPaginator($where = null, $order = null)
    {
        return parent::_getPaginator($where, $order); // TODO: Change the autogenerated stub
    }
}