<?php

namespace Oa\Model;
use Zend\Db\TableGateway\TableGateway;
use Oa\Model\BaseTable;
class UserTable extends BaseTable
{
    public $tableName = 'user';
    public $tableModel = 'Oa\Model\User';

    public function saveAs(User $obj)
    {
        return parent::save($obj); // TODO: Change the autogenerated stub
    }

    public function getPaginator( $where = null , $order = null)
    {
        return parent::_getPaginator( $where , $order); // TODO: Change the autogenerated stub
    }
}



?>
