<?php

namespace Oa\Model;
use Zend\Db\TableGateway\TableGateway;
use Oa\Model\Record;
use Oa\Model\BaseTable ;
class ReportTable extends BaseTable
{
    public $tableName = 'report';
    public $tableModel = 'Oa\Model\Report';

    public function saveAs(Report $obj)
    {
        return parent::save($obj); // TODO: Change the autogenerated stub
    }

    public function getPaginator($where = null, $order = null)
    {
        return parent::_getPaginator($where, $order); // TODO: Change the autogenerated stub
    }


}



?>
