<?php

namespace Oa\Model;
use Zend\Db\TableGateway\TableGateway;
use Oa\Model\BaseTable;
class HistoryTable extends BaseTable
{
    public $tableModel = 'Oa\Model\History';
    public $tableName = 'history';

    public function saveAs(History $obj)
    {
        return parent::save($obj); // TODO: Change the autogenerated stub
    }

    public function getPaginator($where = null, $order = null)
    {
        return parent::_getPaginator($where, $order); // TODO: Change the autogenerated stub
    }
}



?>
